export enum UserRole {
  PASSENGER = 'PASSENGER',
  BOOKING_AGENT = 'BOOKING_AGENT',
  COMPANY_ADMIN = 'COMPANY_ADMIN',
  COMPANY_MANAGER = 'COMPANY_MANAGER',
  DRIVER = 'DRIVER',
  FLEET_MANAGER = 'FLEET_MANAGER',
  CALL_CENTER_AGENT = 'CALL_CENTER_AGENT',
  FINANCE_OFFICER = 'FINANCE_OFFICER',
  SUPER_ADMIN = 'SUPER_ADMIN',
  FRANCHISE_PARTNER = 'FRANCHISE_PARTNER',
  CARGO_OPERATOR = 'CARGO_OPERATOR',
  AIRLINE_OPERATOR = 'AIRLINE_OPERATOR',
  RAILWAY_OPERATOR = 'RAILWAY_OPERATOR',
}

export const ROLE_HIERARCHY = {
  [UserRole.SUPER_ADMIN]: 1000,
  [UserRole.COMPANY_ADMIN]: 900,
  [UserRole.COMPANY_MANAGER]: 800,
  [UserRole.FLEET_MANAGER]: 700,
  [UserRole.FINANCE_OFFICER]: 600,
  [UserRole.CALL_CENTER_AGENT]: 500,
  [UserRole.BOOKING_AGENT]: 400,
  [UserRole.DRIVER]: 300,
  [UserRole.PASSENGER]: 100,
};